name: cute-cat-gallery-ci-pipeline
on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
        with:
          gradle-version: 8.1.1

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew :app:assembleDebug

      - name: Run Lint
        run: ./gradlew ktlintCheck

      - name: Run Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: CuteCatsGallery
          path: app/build/outputs/apk/debug/app-debug.apk
