name: cute-cat-gallery-ci-pipeline
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: build
          gradle-version: 7.2
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: CuteCatsGallery
          path: app/build/outputs/apk/app-debug.apk
